# Generated by Django 5.1 on 2025-08-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('subject', models.CharField(max_length=50)),
                ('enrollment_year', models.CharField(max_length=20)),
                ('highschool_cgpa', models.FloatField()),
                ('eca_interest', models.CharField(max_length=10)),
                ('eca_choice', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.TextField()),
            ],
        ),
    ]
